---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-image-registry-volume
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    storage: image-registry-volume
spec:
  capacity:
    storage: 20G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/registry/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-image-registry-volume-claim
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15G

---

apiVersion: v1
kind: Service
metadata:
  name: kube-image-registry
  namespace: kube-system
  labels:
    k8s-app: kube-image-registry-upstream
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeRegistry"
spec:
  selector:
    k8s-app: kube-image-registry-upstream
  ports:
  - name: registry
    port: 5000
    protocol: TCP

---

# kubectl label nodes le-staging-registry image-registry=true
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-image-registry-v0
  namespace: kube-system
  labels:
    k8s-app: kube-image-registry-upstream
    version: v0
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-image-registry-upstream
    version: v0
  template:
    metadata:
      labels:
        k8s-app: kube-image-registry-upstream
        version: v0
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - name: image-registry
          image: registry:2
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: REGISTRY_HTTP_ADDR
              value: :5000
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: /var/lib/registry
          volumeMounts:
            - name: image-store
              mountPath: /var/lib/registry
          ports:
            - containerPort: 5000
              name: registry
              protocol: TCP
      volumes:
        - name: image-store
          persistentVolumeClaim:
            claimName: kube-image-registry-volume-claim
      nodeSelector:
        role: image-registry

---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-image-registry-proxy
  namespace: kube-system
  labels:
    k8s-app: kube-image-registry-proxy
    kubernetes.io/cluster-service: "true"
    version: v0.4
spec:
  template:
    metadata:
      labels:
        k8s-app: kube-image-registry-proxy
        kubernetes.io/name: "kube-image-registry-proxy"
        kubernetes.io/cluster-service: "true"
        version: v0.4
    spec:
      containers:
        - name: kube-image-registry-proxy
          image: gcr.io/google_containers/kube-registry-proxy:0.4
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
          env:
            - name: REGISTRY_HOST
              value: kube-image-registry.kube-system.svc.cluster.local
            - name: REGISTRY_PORT
              value: "5000"
          ports:
            - name: registry
              containerPort: 80
              hostPort: 5000
              protocol: TCP

# vim: ts=2 sts=2 sw=2
